import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/organism/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Vaxery Coffee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/assets/images/logo.png" sizes="any"/>
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
